const products = [
  {
    name: "Essential Cotton Tee",
    price: 118,
    category: "T-shirt",
    gender: "Men",
    images: [
      "https://plus.unsplash.com/premium_photo-1727942419945-1908baae3c8e?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Relaxed Fit Crew T-Shirt",
    price: 128,
    category: "T-shirt",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1643308004429-ce3793d221a3?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Minimal Graphic Tee",
    price: 143,
    category: "T-shirt",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1682731500074-0a45a3408fc5?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Soft Touch Everyday Tee",
    price: 112,
    category: "T-shirt",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1660983414551-b3758336be15?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Slim Fit Cotton Tee",
    price: 98,
    category: "T-shirt",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1548389995-fbd3151a501f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Classic Ribbed T-Shirt",
    price: 119,
    category: "T-shirt",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1583744999783-efe9dc5eac91?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Relaxed Everyday Tee",
    price: 128,
    category: "T-shirt",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1600328759671-85927887458d?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Soft Lounge T-Shirt",
    price: 96,
    category: "T-shirt",
    gender: "Women",
    images: [
      "https://plus.unsplash.com/premium_photo-1691367279230-22c8f40562e5?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Oversized Fleece Hoodie",
    price: 250,
    category: "Hoodie",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1733322987309-a636b15d1c29?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Minimal Zip Hoodie",
    price: 220,
    category: "Hoodie",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1738486260120-983c44c7703a?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Cropped Fleece Hoodie",
    price: 332,
    category: "Hoodie",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1745825219087-802850857308?q=80&w=686&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Relaxed Fit Hoodie",
    price: 367,
    category: "Hoodie",
    gender: "Women",
    images: [
      "https://plus.unsplash.com/premium_photo-1765263955807-ffad475d0e9e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Soft Touch Hoodie",
    price: 312,
    category: "Hoodie",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1708533644535-fcf447ac0cad?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Essential Pullover Hoodie",
    price: 292,
    category: "Hoodie",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1606156303121-d120291045cd?q=80&w=716&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Structured Wool Blend Jacket",
    price: 392,
    category: "Jacket",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1680350024350-fb635c48caaf?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Lightweight Everyday Jacket",
    price: 312,
    category: "Jacket",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1644483878413-1bdfe8d1180c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Relaxed Fit Outer Jacket",
    price: 378,
    category: "Jacket",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1754746804782-fcf470a9b5e7?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Classic Fit Utility Jacket",
    price: 335,
    category: "Jacket",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1630797160982-553facf1c3cc?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Minimal Bomber Jacket",
    price: 332,
    category: "Jacket",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1724335141947-a63578d5d118?q=80&w=706&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Everyday Zip Jacket",
    price: 379,
    category: "Jacket",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1643308002958-6fc02613aa5c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Slim Fit Denim Jeans",
    price: 152,
    category: "Jeans",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1721665107649-11e9773821b9?q=80&w=715&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Regular Fit Blue Jeans",
    price: 167,
    category: "Jeans",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1754555009601-498e9873197e?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "High Waist Straight Jeans",
    price: 178,
    category: "Jeans",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1578693082747-50c396cacd81?q=80&w=715&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Classic Fit Denim Jeans",
    price: 188,
    category: "Jeans",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1738618806206-b2cb6331193c?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Relaxed Fit Mom Jeans",
    price: 164,
    category: "Jeans",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1628519662791-c13362859149?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Classic Street Sneakers",
    price: 266,
    category: "Shoes",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1595388710140-e7b90300ec73?q=80&w=766&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Minimal White Sneakers",
    price: 242,
    category: "Shoes",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1559334417-01b38aec66bd?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Chunky Sole Sneakers",
    price: 332,
    category: "Shoes",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1643758344142-7933a8c07796?q=80&w=830&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
  {
    name: "Everyday Comfort Sneakers",
    price: 339,
    category: "Shoes",
    gender: "Men",
    images: [
      "https://images.unsplash.com/photo-1726835479857-68943bccbf94?q=80&w=715&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
    isFeatured: true,
  },
  {
    name: "Lightweight Running Sneakers",
    price: 278,
    category: "Shoes",
    gender: "Women",
    images: [
      "https://images.unsplash.com/photo-1553808373-92b0bcc3af65?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    sizes: [
      { size: "XS", stock: Math.floor(Math.random() * 10) },
      { size: "S", stock: Math.floor(Math.random() * 10) },
      { size: "M", stock: Math.floor(Math.random() * 10) },
      { size: "L", stock: Math.floor(Math.random() * 10) },
      { size: "XL", stock: Math.floor(Math.random() * 10) },
      { size: "XXL", stock: Math.floor(Math.random() * 10) },
    ],
  },
];

module.exports = products;
